name: uidisign05
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  animations: ^2.0.11

  # ðŸ‘‰ tambahan untuk fitur tracker makanan
  shared_preferences: ^2.2.3
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/font/SF-Pro-Display-Black.ttf
        - asset: assets/font/SF-Pro-Display-Bold.ttf
        - asset: assets/font/SF-Pro-Display-Light.ttf
        - asset: assets/font/SF-Pro-Display-Medium.ttf
        - asset: assets/font/SF-Pro-Display-Regular.ttf
        - asset: assets/font/SF-Pro-Display-Semibold.ttf
        - asset: assets/font/SF-Pro-Display-Thin.ttf
        - asset: assets/font/SF-Pro-Display-Ultralight.ttf
